---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-openshift-io-v1-dpuoperatorconfig
  failurePolicy: Fail
  name: vdpuoperatorconfig.kb.io
  rules:
  - apiGroups:
    - config.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dpuoperatorconfigs
  sideEffects: None
