apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dpu-daemon
  namespace: {{.Namespace}}
spec:
  selector:
    matchLabels:
      app: dpu-daemon
  template:
    metadata:
      labels:
        app: dpu-daemon
        component: network
        type: infra
    spec:
      serviceAccountName: dpu-daemon-sa
      hostNetwork: true
      hostPID: true
      nodeSelector:
        dpu: "true"
      securityContext:
        privileged: true
      containers:
      - name: dpu-daemon
        image: {{.DpuOperatorDaemonImage}}
        securityContext:
          privileged: true
        imagePullPolicy: {{.ImagePullPolicy}}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IntelVspImage
          value: {{.IntelVspImage}}
        - name: IntelVspP4Image
          value: {{.IntelVspP4Image}}
        - name: MarvellVspImage
          value: {{.MarvellVspImage}}
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: dpu-daemon-mount
          mountPath: /var/run/dpu-daemon
          mountPropagation: Bidirectional
        - name: var-cni-dir
          mountPath: /var/lib/cni
        - name: opt-cni-dir
          mountPath: /opt/cni
        - name: host-run
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: proc
          mountPath: /proc
        args:
        - --mode
        - {{.Mode}}
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: dpu-daemon-mount
          hostPath:
            path: /var/run/dpu-daemon
        - name: var-cni-dir
          hostPath:
            path: /var/lib/cni
        - name: opt-cni-dir
          hostPath:
            path: /opt/cni
        - name: host-run
          hostPath:
            path: /var/run/netns
        - name: proc
          hostPath:
            path: /proc/
