apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dpu-operator
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  template:
    spec:
      containers:
      - command:
        name: manager
        env:
        - name: DPU_DAEMON_IMAGE
          value: {{ .RegistryURL }}:5000/dpu-daemon:dev-incremental
        - name: IntelVspImage
          value: {{ .RegistryURL }}:5000/intel-vsp:dev-incremental
        - name: MarvellVspImage
          value: {{ .RegistryURL }}:5000/mrvl-vsp:dev-incremental
        - name: IMAGE_PULL_POLICIES
          value: Always
        - name: NETWORK_RESOURCES_INJECTOR_IMAGE
          value: {{ .RegistryURL }}:5000/network-resources-injector:dev-incremental
        image: {{ .RegistryURL }}:5000/dpu-operator:dev-incremental
        imagePullPolicy: Always
