apiVersion: v1
kind: Service
metadata:
  name: network-resources-injector-service
  namespace: {{.Namespace}}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: "network-resources-injector-secret"
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: network-resources-injector
