---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: network-resources-injector-config
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: network-resources-injector-config.k8s.io
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: network-resources-injector-service
        namespace: {{.Namespace}}
        path: "/mutate"
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: "NotIn"
          values:
            - {{.Namespace}}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
