apiVersion: v1
kind: Secret
metadata:
  name: network-resources-injector-sa-secret
  namespace: {{.Namespace}}
  annotations:
    kubernetes.io/service-account.name: network-resources-injector-sa
type: kubernetes.io/service-account-token
