apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-resources-injector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - 'watch'
  - 'list'
  - 'get'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - 'get'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - 'watch'
  - 'list'
  - 'get'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - hostnetwork
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - 'use'
