apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-resources-injector-webhook-configs-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-resources-injector-webhook-configs
subjects:
- kind: ServiceAccount
  name: network-resources-injector-sa
  namespace: {{.Namespace}}
