apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-resources-injector
  name: network-resources-injector
  namespace: {{.Namespace}}
spec:
  selector:
    matchLabels:
      app: network-resources-injector
  template:
    metadata:
      labels:
        app: network-resources-injector
    spec:
      serviceAccount: network-resources-injector-sa
      containers:
      - name: webhook-server
        image: {{.NRIWebhookImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        command:
        - /webhook
        args:
        - -bind-address=0.0.0.0
        - -port=8443
        - -tls-private-key-file=/etc/tls/tls.key
        - -tls-cert-file=/etc/tls/tls.crt
        - -insecure=true
        - -health-check-port=8444
        - -logtostderr
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: true
          capabilities:
            drop:
              - ALL
            add: ["NET_BIND_SERVICE"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/tls
          name: tls
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8444
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: tls
        secret:
          secretName: network-resources-injector-secret
